name: test-and-build-actions
on:
  push:
    branches: [ "main" ]
jobs:
  test_and_build:
    name: test_and_build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: npm install & test & build
        run:  |
          npm install
          npm run test
          npm run build
      - name: upload dist file
        uses: actions/upload-artifact@v3
        with:
          name: upload dist file
          path: dist
